
# Glashammer Declaration File


# Load any plugins for Glashammer, we want SQLAlchemy db support.

bundles:
    - sqlalchdb


# Where to look for templates. Relative paths are taken relative to the path
# that this declaration file lives in.

template_searchpaths:
    - templates


# Template filters to be imported and registered. Any importable Python
# callable which takes a string and returns one can be a filter, for
# example creoleparser for generating HTML from wiki text can be used without
# any glue code:

template_filters:
    - name: text2html
      filter: creoleparser.text2html


# Set up the urls for the application. The view is any importable Python callable.
# Urls are the Werkzeug rule

urls:

 - url: /
   endpoint: index
   view: views.view_index

 - url: /<string:page_name>
   endpoint: show
   view: views.view_show

 - url: /<string:page_name>/edit
   endpoint: edit
   view: views.view_edit

 - url: /new
   endpoint: new
   view: views.view_new

appliances:
    - import: glashammer.appliances.admin.appliance
      mountpoint_path: /admin

